spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/information
    username: postgres
    password: 12345
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

  application:
    name: info-data